### ISSUE TITLE
An example would be good!

### ISSUE THREAD

**Issue by lockhartsoftware** [AlienHack/BlazorHero-Helper#1]
An example would be good!

**Comment by AlienHack** [comment]
> An example would be good!

Okay, will update readme and wiki on how to use !

**Comment by lockhartsoftware** [comment]
Thank you.

I should’ve said earlier, it looks a really useful time-saver.

**Comment by AlienHack** [comment]
> Thank you.
> 
> I should’ve said earlier, it looks a really useful time-saver.

A simple guide is available!

https://github.com/AlienHack/BlazorHero-Helper/wiki/How-To-Use

**Comment by lockhartsoftware** [comment]
Thank you.
