### ISSUE TITLE
Bug in Permission

### ISSUE THREAD

**Issue by gurolgencel** [AlienHack/BlazorHero-Helper#4]
Hello ,

Search permission template has a bug, you can edit as follow;

```
public static class $_ENTITY_$s
        {
            public const string View = ""Permissions.$_ENTITY_$s.View"";
            public const string Create = ""Permissions.$_ENTITY_$s.Create"";
            public const string Edit = ""Permissions.$_ENTITY_$s.Edit"";
            public const string Delete = ""Permissions.$_ENTITY_$s.Delete"";
            public const string Search = ""Permissions.$_ENTITY_$s.Search"";
        }";
```

**Comment by gozilla-paradise** [comment]
> Hello ,
> 
> Search permission template has a bug, you can edit as follow;
> 
> ```
> public static class $_ENTITY_$s
>         {
>             public const string View = ""Permissions.$_ENTITY_$s.View"";
>             public const string Create = ""Permissions.$_ENTITY_$s.Create"";
>             public const string Edit = ""Permissions.$_ENTITY_$s.Edit"";
>             public const string Delete = ""Permissions.$_ENTITY_$s.Delete"";
>             public const string Search = ""Permissions.$_ENTITY_$s.Search"";
>         }";
> ```

fixed on latest commit!
